### PR TITLE
Add vo-list command

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
### Initial checklist

*   [X] I read the support docs 
*   [X] I read the contributing guide 
*   [X] I agree to follow the code of conduct 
*   [X] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [X] If applicable, I’ve added docs and tests

### Description of changes

Added a new command to filter sites in the EGI Federated Cloud supporting a VO

### CODE REVIEW

**Review by tdviet — COMMENTED** [review]
@sebastian-luna-valero thank very much for the PR. My first thought of `fedcloud site vo-list` is about listing the VO supported on a given site. What about merging the new command

**Comment by sebastian-luna-valero** [comment]
Thanks for your feedback @tdviet 

> What about merging the new command which the fedcloud site list command, i.e. fedcloud site list --vo VO where if the --vo option is omitted, it will print all sites, if present, print only sites supported the VO.

That was my initial attempt, but I then realised that the `vo_params` decorator is required:

https://github.com/tdviet/fedcloudclient/blob/0f875dee109eb5376756a0547f96f85341a1f7ab/fedcloudclient/decorators.py#L98

Therefore, adding it to the existing `list` command for sites will return:

```bash
$ fedcloud site list
Usage: fedcloud site list [OPTIONS]
Try 'fedcloud site list --help' for help.

Error: Missing option '--vo'.
```

That's why I created a new command. However, agree the naming might be confusing. Instead how should I call it to make it more intuitive?

**Comment by tdviet** [comment]
What about creating a new decorator for `--vo` parameter without the `required`, e.g. `vo_params_unquired`. I don't think there will be any conflicts between decorators

**Comment by sebastian-luna-valero** [comment]
Done!

> I don't think there will be any conflicts between decorators

That was exactly my concerned and I didn't test it. Seems to work well, please check.

**Review by tdviet — APPROVED** [review]
LGTM

**Pull request merged**
