### PR TITLE
Formatted output of commands that return shell code to set env vars

### LINKED ISSUE #61: Linux-specific command output
Some commands output Linux commands to export environment variables (including the value of the variable which is the useful output of the command). When run on Windows machines (from CMD or PowerShell) the output should be different, so that it is immediately usable on the host platform.

### PR DESCRIPTION
**Pull request by thebe14**
Closes #61

### CODE REVIEW

**Comment by thebe14** [comment]
Please publish a new version of the fedcloudclient with these improvements. The usage of this improvement is described in the EGI docs at https://docs.egi.eu/users/getting-started/cli/#using-in-scripts.

**Comment by tdviet** [comment]
Merged. BTW, nicely presented documentation at https://docs.egi.eu/users/getting-started/cli/#using-in-scripts. I should have done it but couldn't find time to do. Thanks.

**Comment by thebe14** [comment]
@tdviet Wait until [this PR](https://github.com/EGI-Federation/documentation/pull/313) is merged into the EGI docs, then that page will also reflect this new fedcloud feature. You can also see a [preview](https://docs.egi.eu/documentation/313/users/getting-started/cli/#using-in-scripts) before it is merged (sorry for the scroll bug, that is also fixed now in another documentation PR)

**Comment by tdviet** [comment]
A new release (1.2.8) has been published to PyPi to make the documentation actual.

**Pull request merged**
