### PR TITLE
Add image sync fields to schema

### PR DESCRIPTION
**Pull request by enolfc**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests

### Description of changes

Added new fields for image synchronisation (see https://github.com/EGI-Federation/fedcloud-catchall-operations/pull/350)

### CODE REVIEW

**Review by tdviet — COMMENTED** [review]
Hi Enol, do you plan to have the list of images as a part of site configuration? For what purpose?

**Comment by enolfc** [comment]
Not the list of images, but whether to configure image synchronisation or not in the catchall instance.

**Comment by enolfc** [comment]
See sample config https://github.com/EGI-Federation/fedcloud-catchall-operations/blob/5f01874961fb46a5f98e4cb4946fa3422718f560/sites/WALTON-CLOUD.yaml

**Review by tdviet — APPROVED** [review]
LGTM

**Pull request merged**
